### ISSUE TITLE
Fix grocery list bullet points extending outside container boxes

### ISSUE THREAD

**Issue by ryan-miles** [ryan-miles/meals.stellation.one#2]
## Issue Description
The bullet points on the grocery list page (week.html) are extending too far to the left, appearing outside of their containing boxes.

## Current Behavior
- Unordered list bullets in the grocery list sections (Freezer, Refrigerator, Pantry) stick out beyond the left edge of their container boxes
- This creates a visual layout issue where bullets appear disconnected from their content

## Root Cause
The CSS styling for `.card.bento-box ul.grocery-list` has insufficient left padding/margin to accommodate the bullet points within the container boundaries.

## Proposed Solution
Update the CSS rules for the grocery list to ensure proper indentation:

```css
.card.bento-box ul.grocery-list {
  padding-left: 2.5em;  /* Increased from 1.7em */
  padding-inline-start: 2.5em;  /* Increased from 1.7em */
  margin-left: 0;
  background: transparent;
  list-style-position: outside;
  width: auto;
}
```

Alternatively, if you want to keep bullets closer to the text but still within the container:

```css
.card.bento-box ul.grocery-list {
  padding-left: 0;
  margin-left: 2em;  /* Use margin instead of padding */
  background: transparent;
  list-style-position: outside;
  width: auto;
}
```

## Files Affected
- `website/css/styles.css` - Lines around 786-793

## Testing
After implementing the fix, verify that:
1. Bullet points appear within the container boundaries
2. Text alignment remains consistent
3. Responsive behavior is maintained on mobile devices
